server:
    # context-path: /zmanager
    session-timeout: 1800
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8081
    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    encoding: utf-8
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true
  messages:
    basename: i18n/Messages,i18n/Pages
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.zmanager.**.domain
